version: '3.3'

services:
  db_postgre:
    build: ./postgresql-postgis
    image: postgres:11
    container_name: postgresql-postgis-container
    ports:
    - 5432:5432
    restart: always
    networks:
    - eb

  tomcat_eb:
    build:
      context:  .
      dockerfile: ./tomcat/Dockerfile
    image: tomcat-eb:v.9
    container_name: tomcat-eb-container
    ports:
    - 8888:8080
    restart: on-failure
    depends_on:
    - db_postgre
    networks:
    - eb

volumes:
  pg_data:

networks:
  eb: